### ISSUE TITLE
Record button not working

### ISSUE THREAD

**Issue by aissar** [PinkyJie/aws-transcribe-demo#4]
<img width="560" alt="Screen Shot 2019-07-05 at 2 21 32 pm" src="https://user-images.githubusercontent.com/37895090/60697928-36e90c00-9f30-11e9-8aa5-cf2c49bfcb6b.png">
Record button not working. Have tried on latest version of Chrome and Safari browser. Have also checked browser privacy settings, which are not blocking microphone etc.

**Comment by PinkyJie** [comment]
Hi @aissar , sorry for the late response. Could you explain your issues in detail? I just released a new version, previous version will always download a `txt` file. Here is the demo site https://d3hk9i6re8qnvi.cloudfront.net, I tried it with my Chrome v76, it works, could you try again?

**Comment by aissar** [comment]
Hi @PinkyJie thanks for looking into this issue. I'm now able to successfully record audio from my Mac (tested with Chrome browser). This was not working previously but seems to be working now as per the demo site link above. 

Note, the issue still persists when attempting to record audio from iPhone (tested with Chrome and Safari browsers).

**Comment by PinkyJie** [comment]
Hi @aissar , right now I use `MediaRecorder` API, it only supports Chrome and Firefox, (https://caniuse.com/#feat=mediarecorder), that's why it does not work on other browsers.

**Comment by aissar** [comment]
Awesome! Thanks for the info above.
